### ISSUE TITLE
Pylivetrader fails to call `order_target_percent` if there are untradable stocks

### ISSUE THREAD

**Issue by jeefy** [alpacahq/pylivetrader#178] opened 2020-07-14 16:54 UTC
If your portfolio has stocks that are stuck/untradable, and you attempt any sort of `order_target_percent` action, Pylivetrader crashes when it attempts to lookup the stock price of said-stuck-stock. 

It doesn't matter how large or small the percent is, when the `order_target_percent` method is invoked it tries to evaluate the size of the portfolio (ie lookup the existing stocks) and the whole action fails.

**Comment by shlomikushchi** [comment] 2020-07-29 16:01
Hi @jeefy sorry for the late response. 
do you have an example of such stock I could test locally?

**Comment by jeefy** [comment] 2020-07-29 18:06
Yep! In my case I have LTMAQ and CHKAQ that I was holding and then became
untradable. :(

Thanks!

**Comment by shlomikushchi** [comment] 2020-07-29 19:29
this is what I get when I try to trade one of these: 
```[2020-07-29 19:28:35.269820] WARNING: Algorithm: Cannot place order for LTMAQ, as it is not tradable.```
it doesn't trade, but it also doesn't crash

**Comment by shlomikushchi** [comment] 2020-08-03 08:23
do you have an idea on how to reproduce your error?

**Comment by krishnathon2006** [comment] 2020-08-26 15:41
I have the same error when I'm trying to liquidate long position of VVPR using ```   
 for s in context.portfolio.positions:
        order_target_percent(s, 0)``` and getting next stack track.
After this error happen, execution of the script stops and non of my stocks sold.
```
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
ERROR:root:error while consuming ws messages: consume cancelled
[2020-08-26 13:31:01.422532] INFO: builtins: Selling:VVPR
[2020-08-26 13:31:01.760584] ERROR: Executor: Cannot order VVPR, as it not tradable
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "pylivetrader_compatible.py", line 48, in my_rebalance
    order_target_percent(s, 0)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 621, in order_target_percent
    amount = self._calculate_order_target_percent_amount(asset, target)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 860, in _calculate_order_target_percent_amount
    target_amount = self._calculate_order_percent_amount(asset, target)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 850, in _calculate_order_percent_amount
    return self._calculate_order_value_amount(asset, value)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 825, in _calculate_order_value_amount
    msg="Cannot order {0}, as it not tradable".format(asset.symbol)
pylivetrader.errors.CannotOrderDelistedAsset: Cannot order VVPR, as it not tradable
[2020-08-26 13:31:01.765499] WARNING: Executor: Continuing execution
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
ERROR:root:error while consuming ws messages: consume cancelled
```

**Comment by shlomikushchi** [comment] 2020-08-30 15:17
Hi,
so if the equity is not tradable, it's beyond the scope of this project (it's not tradable)
about your exception - you should wrap your code (in handle_data() or any other method you run your logic in) with try, except blocks to make sure that even something like this happens it doesn't break your execution.

so something like that:
```py
def handle_data(context, data):
    for s in context.portfolio.positions: 
        try:
            order_target_percent(s, 0)
        except Exception as e:
            logger.error(f"failed closing position with: {e}")
```

**Comment by krishnathon2006** [comment] 2020-08-30 18:22
@shlomikushchi 
> so if the equity is not tradable, it's beyond the scope of this project (it's not tradable)

The equity IS tradable, however due to some issues (e.g. consume cancelled) pylivetrader treat all equities in my portfolio as non-tradable.

> about your exception - you should wrap your code (in handle_data() or any other method you run your logic in) with try, except blocks to make sure that even something like this happens it doesn't break your execution.

This suggestion will not help and my script will not not be able to buy/sell anyway because pylivetrader failed to fetch asset information. This is the point of my script - to buy and sell, so I cannot just skip it. I'd rather prefer us to focus on fixing the root cause of data fetch failure.

Maybe this will help you. In any day when I have no issues with execution, I see this logs before sales:
```
[2020-08-19 05:07:03.128234] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
[2020-08-19 13:31:02.237490] INFO: builtins: Selling:ORCL
[2020-08-19 13:31:06.793771] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=8
/home/ubuntu/.zipline/data/dailycache/alpaca_chart_8: digest mismatch 14dd14063fd1211276bc609bddea81a6 != 513a20de027b27cb3ba5b7652dc3a33a, reloading
[2020-08-19 13:31:42.469188] DEBUG: pipeline_live.data.sources.util: fetch: 11.36% completed
[2020-08-19 13:31:52.502865] DEBUG: pipeline_live.data.sources.util: fetch: 20.45% completed
[2020-08-19 13:31:54.981536] DEBUG: pipeline_live.data.sources.util: fetch: 31.81% completed
[2020-08-19 13:32:02.325348] DEBUG: pipeline_live.data.sources.util: fetch: 40.90% completed
[2020-08-19 13:32:08.537197] DEBUG: pipeline_live.data.sources.util: fetch: 52.27% completed
[2020-08-19 13:32:12.048072] DEBUG: pipeline_live.data.sources.util: fetch: 61.36% completed
[2020-08-19 13:32:18.604175] DEBUG: pipeline_live.data.sources.util: fetch: 70.45% completed
[2020-08-19 13:32:24.590102] DEBUG: pipeline_live.data.sources.util: fetch: 81.82% completed
[2020-08-19 13:32:28.565192] DEBUG: pipeline_live.data.sources.util: fetch: 90.91% completed
[2020-08-19 13:32:30.838573] DEBUG: pipeline_live.data.sources.util: fetch: 100.00% completed
[2020-08-19 13:32:39.547205] DEBUG: Alpaca: submitting market order for AAPL - qty:1, side:buy, limit_price:None, stop_price:None
```
but in a day when it does not work it looks like:
```
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
ERROR:root:error while consuming ws messages: [Errno 111] Connect call failed ('35.194.67.18', 443)
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
ERROR:root:error while consuming ws messages: consume cancelled
[2020-08-26 13:31:01.422532] INFO: builtins: Selling:VVPR
[2020-08-26 13:31:01.760584] ERROR: Executor: Cannot order VVPR, as it not tradable
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "pylivetrader_compatible.py", line 48, in my_rebalance
    order_target_percent(s, 0)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 621, in order_target_percent
    amount = self._calculate_order_target_percent_amount(asset, target)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 860, in _calculate_order_target_percent_amount
    target_amount = self._calculate_order_percent_amount(asset, target)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 850, in _calculate_order_percent_amount
    return self._calculate_order_value_amount(asset, value)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 825, in _calculate_order_value_amount
    msg="Cannot order {0}, as it not tradable".format(asset.symbol)
pylivetrader.errors.CannotOrderDelistedAsset: Cannot order VVPR, as it not tradable
[2020-08-26 13:31:01.765499] WARNING: Executor: Continuing execution
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
ERROR:root:error while consuming ws messages: consume cancelled
```

**Comment by shlomikushchi** [comment] 2020-08-30 19:11
the websocket issues are not related to "tradable" issues.
pylivetrader checks if an asset is tradable through the REST API so they use different routes.
it looks like there were connectivity issues that day.
maybe it's related if you couldn't connect to both REST api and WS api
but basically if I understand this correctly, we deal with 2 unrelated issues

**Comment by shlomikushchi** [comment] 2020-09-01 17:28
also :
![image](https://user-images.githubusercontent.com/7924802/91886254-bdfb5680-ec91-11ea-9931-72b6056226ef.png)

**Comment by krishnathon2006** [comment] 2020-09-02 02:26
The fact that VVPR is marked as not tradable on screenshot is very interesting.
I can trade it manually using alpaca UI and when I make a call to get a list of assets it is return it as tradable:
```
api = tradeapi.REST('<key>', '<secret>', , base_url='https://paper-api.alpaca.markets')
api.list_assets()
```
with result:
```
Asset({   'class': 'us_equity',
    'easy_to_borrow': False,
    'exchange': 'NASDAQ',
    'id': 'fc8d427a-13df-4c7b-a26d-480079fc5ae8',
    'marginable': True,
    'name': 'VivoPower International PLC Ordinary Shares',
    'shortable': False,
    'status': 'active',
    'symbol': 'VVPR',
    'tradable': True}) <----------
```

**Comment by shlomikushchi** [comment] 2020-09-02 11:22
so that might mean we a bug inside pylivetrader marking it as not tradable. I will check it.

**Comment by szheng3** [comment] 2020-09-15 16:12
i also have the same problem. [2020-09-15 15:07:06.867731] ERROR: Executor: Cannot order TMF, as it not tradable
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 236, in handle_data
    self._handle_data(self, data)
  File "algo.py", line 64, in handle_data
    order_target_percent(tmf_symbol, 0.3)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 621, in order_target_percent
    amount = self._calculate_order_target_percent_amount(asset, target)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 860, in _calculate_order_target_percent_amount
    target_amount = self._calculate_order_percent_amount(asset, target)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 850, in _calculate_order_percent_amount
    return self._calculate_order_value_amount(asset, value)
  File "/usr/local/anaconda3/envs/trade/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 825, in _calculate_order_value_amount
    msg="Cannot order {0}, as it not tradable".format(asset.symbol)
pylivetrader.errors.CannotOrderDelistedAsset: Cannot order TMF, as it not tradable

**Comment by dsinyakov** [comment] 2020-09-17 16:47
Another hint. The problem I believe is not in `order_target_percent` method logic. As I stated in #192 is that `symbol` method returns the wrong version of ticker. In my case there are two VXX symbols returned through regular alpaca API, on is tradable another is not. While in pylivetrader `symbol` method always returns the un-tradable one.   There might be also similar problem in `order` method that  `order_target_percent` calls into. Cause if I hardcode the tradable symbol of VXX, I still end up with positions open for un-tradable one.

**Comment by shlomikushchi** [comment] 2020-09-18 18:07
Hi, can_trade was fixed and now should not be an issue.
you should be able to trade it.

**Comment by shlomikushchi** [comment] 2020-09-18 18:08
you can get the updated version directly from github or wait for the release process to pypi.

**Comment by krishnathon2006** [comment] 2020-09-22 01:32
@shlomikushchi When should we expect 0.5.1 to be released and available in pypi?

**Comment by shlomikushchi** [comment] 2020-09-22 12:21
soon,
you could already install it directly from github like this:
`pip install -U git+https://github.com/alpacahq/pylivetrader`

**Comment by camelpac** [comment] 2021-05-29 14:03
closing due to lack of activity. please re-open if still relevant

**Closed by camelpac** 2021-05-29 14:03 UTC
