### ISSUE TITLE
API access error

### ISSUE THREAD

**Issue by reedv** [alpacahq/pylivetrader#66] opened 2018-12-17 02:30 UTC
Running the code for [example q01](https://github.com/alpacahq/pylivetrader/tree/master/examples/q01) (using config.yaml file rather than exporting environment variables) throws the following error:

```bash
(myvirtualenv) ➜  src pylivetrader run -f algo.py --backend-config ../relative/path/to/config.yaml 

[2018-12-17 02:13:35.133648] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Traceback (most recent call last):
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 113, in _one_request
    resp.raise_for_status()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.alpaca.markets//v1/assets?assert_class=us_equity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/python-virtualenvs/myvirtualenv/bin/pylivetrader", line 11, in <module>
    sys.exit(main())
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/__main__.py", line 144, in run
    algorithm.run(retry=ctx.retry)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 232, in run
    self.asset_finder.retrieve_all(self.asset_finder.sids)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/assets/finder.py", line 192, in sids
    for sid, _ in self._asset_cache.items()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/assets/finder.py", line 38, in _asset_cache
    for asset in self.backend.get_equities()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/backend/alpaca.py", line 130, in get_equities
    raw_assets = self._api.list_assets(asset_class='us_equity')
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 218, in list_assets
    resp = self.get('/assets', params)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 129, in get
    return self._request('GET', path, data)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 92, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 121, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: access key verification failed : access key not found (Code = 40110000) (Code = 40110000)
```
Am using the public and secret API keys from Alpaca account for _paper trading_, eg.

```bash
(myvirtualenv) ➜  src cat ../relative/path/to/config.yaml
key_id: XXXXXX
secret: XXXXXX/XXXXXX/XXXXXX
base_url: https://api.alpaca.markets/
```
Copying the same format as here (https://github.com/alpacahq/pylivetrader#simple-usage) (using `base_url: https://api.alpaca.markets` without trailing `/` does not help either, nor does removing the `base_url` peoperty from the .yaml). Exporting the values to environment as in the [original example](https://github.com/alpacahq/pylivetrader/tree/master/examples/q01#how-to-run-your-algorithm) does not work either.

**Comment by reedv** [comment] 2018-12-17 02:41
**Resolved: Was using incorrect `base_url` value in .yaml config file**. Looking at Alpaca web UI can see need different API endpoint for paper trading. Now have .yaml file like

```bash
(myvirtualenv) ➜  src cat ../relative/path/to/config.yaml
key_id: XXXXXX
secret: XXXXXX/XXXXXX/XXXXXX
base_url: https://paper-api.alpaca.markets
```
and things appear to function as expected.

**Comment by umitanuki** [comment] 2018-12-17 05:39
Thanks for the updates. We are working on clearer instruction and improvement on experience.

**Comment by reedv** [comment] 2018-12-17 17:44
Testing today on actual market open, it appears that the problem is not resolved, seeing the following error message:

```bash
(myvirtualenv) ➜  src pylivetrader run -f algo.py --backend-config ../relative/path/to/config.yaml  -l 'DEBUG'
[2018-12-17 17:34:53.496023] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
0
[2018-12-17 17:34:55.808817] INFO: algo: 
        Algorithm initialized variables:
            context.MaxCandidates 100
            LowVar 6
            HighVar 40
        
[2018-12-17 17:34:55.812639] INFO: algo: 
        Algorithm selected stocks NumExprFilter(expr='x_0 <= (100.0)', bindings={'x_0': Rank(NumExprFactor(expr='(x_0 - x_1) / (x_1)', bindings={'x_1': SimpleMovingAverage([USEquityPricing.close], 45), 'x_0': SimpleMovingAverage([USEquityPricing.close], 3)}), method='ordinal', mask=AssetExists())})
        
[2018-12-17 17:34:57.309327] INFO: pipeline_live.data.iex.pricing_loader: chart_range=3m
Traceback (most recent call last):
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 113, in _one_request
    resp.raise_for_status()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.alpaca.markets/v1/assets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/python-virtualenvs/myvirtualenv/bin/pylivetrader", line 11, in <module>
    sys.exit(main())
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/__main__.py", line 144, in run
    algorithm.run(retry=ctx.retry)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 242, in run
    return self.executor.run(retry=retry)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/executor/executor.py", line 120, in run
    algo.before_trading_start(self.current_data)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 215, in before_trading_start
    self._before_trading_start(self, data)
  File "algo.py", line 204, in before_trading_start
    context.output = pipeline_output('my_pipeline')
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 1049, in pipeline_output
    output = eng.run_pipeline(self._pipelines[name])
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pipeline_live/engine.py", line 77, in run_pipeline
    initial_workspace,
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pipeline_live/engine.py", line 252, in compute_chunk
    mask,
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/zipline/pipeline/mixins.py", line 214, in _compute
    compute(date, masked_assets, out_row, *inputs, **params)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pipeline_live/data/polygon/filters.py", line 12, in compute
    company = polygon.company()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pipeline_live/data/sources/polygon.py", line 16, in company
    all_symbols = list_symbols()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/pipeline_live/data/sources/polygon.py", line 10, in list_symbols
    a.symbol for a in tradeapi.REST().list_assets()
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 218, in list_assets
    resp = self.get('/assets', params)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 129, in get
    return self._request('GET', path, data)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 92, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/me/python-virtualenvs/myvirtualenv/lib/python3.5/site-packages/alpaca_trade_api/rest.py", line 121, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: access key verification failed : access key not found (Code = 40110000) (Code = 40110000)
```

and the .yaml config file still looks as shown before

```bash
(myvirtualenv) ➜  src cat ../relative/path/to/config.yaml
key_id: XXXXXX
secret: XXXXXX/XXXXXX/XXXXXX
base_url: https://paper-api.alpaca.markets
```

It appears as though the config file is being ignored (at least the `base_url` value anyway). Note that the algo.py file is just the code from [example q01](https://github.com/alpacahq/pylivetrader/tree/master/examples/q01).

**Comment by umitanuki** [comment] 2018-12-17 21:09
I believe this is a duplicate of #29.

As a workaround until it's fixed, please use environment variable to set API key and base url.

**Closed by umitanuki** 2018-12-17 21:09 UTC

**Comment by zoakes** [comment] 2020-05-27 20:46
I have same issue -- how can this be resolved?

HTTPError: 401 Client Error: Unauthorized for url: https://paper-api.alpaca.markets/v2/positions

**Comment by taeyurl** [comment] 2022-06-05 09:27
Can I please get help regarding the issue below which is HTTP related as well...

zipline-trader/zipline/data/bundles/alpaca_api.py:272: UserWarning: Overwriting bundle with name 'alpaca_api'
  def api_to_bundle(interval=['1m']):
zipline-trader/zipline/data/bundles/alpaca_api.py:350: UserWarning: Overwriting bundle with name 'alpaca_api'
  end_session=end_date
Merging daily equity files:  [------------------------------------]    0%
Traceback (most recent call last):
  File "zipline-trader/zipline/data/bundles/alpaca_api.py", line 358, in <module>
    show_progress=True,
  File "c:\zipline-demo\zipline-trader\zipline\data\bundles\core.py", line 513, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "zipline-trader/zipline/data/bundles/alpaca_api.py", line 302, in ingest
    daily_bar_writer.write(daily_data_generator(), assets=assets_to_sids.values(), show_progress=True)
  File "c:\zipline-demo\zipline-trader\zipline\data\bcolz_daily_bars.py", line 207, in write
    return self._write_internal(it, assets)
  File "c:\zipline-demo\zipline-trader\zipline\data\bcolz_daily_bars.py", line 269, in _write_internal
    for asset_id, table in iterator:
  File "c:\zipline-demo\zipline-trader\zipline\data\bcolz_daily_bars.py", line 264, in iterator
    for asset_id, table in iterator:
  File "C:\zipline-demo\venv-demo\lib\site-packages\click\_termui_impl.py", line 328, in generator
    for rv in self.iter:
  File "c:\zipline-demo\zipline-trader\zipline\data\bcolz_daily_bars.py", line 198, in <genexpr>
    (sid, self.to_ctable(df, invalid_data_behavior))
  File "zipline-trader/zipline/data/bundles/alpaca_api.py", line 295, in <genexpr>
    return (sid_df for (sid_df, *metadata.iloc[sid_df[0]]) in df_generator(interval='1d',
  File "zipline-trader/zipline/data/bundles/alpaca_api.py", line 234, in df_generator
    df: pd.DataFrame = get_aggs_from_alpaca(partial, start, end, 'day' if interval == '1d' else 'minute', 1)
  File "zipline-trader/zipline/data/bundles/alpaca_api.py", line 199, in get_aggs_from_alpaca
    response = _iterate_api_calls()
  File "zipline-trader/zipline/data/bundles/alpaca_api.py", line 119, in _iterate_api_calls
    end=curr.isoformat()
  File "C:\zipline-demo\venv-demo\lib\site-packages\alpaca_trade_api\rest.py", line 513, in get_barset
    resp = self.data_get('/bars/{}'.format(timeframe), params)
  File "C:\zipline-demo\venv-demo\lib\site-packages\alpaca_trade_api\rest.py", line 193, in data_get
    'GET', path, data, base_url=base_url, api_version=api_version,
  File "C:\zipline-demo\venv-demo\lib\site-packages\alpaca_trade_api\rest.py", line 139, in _request
    return self._one_request(method, url, opts, retry)
  File "C:\zipline-demo\venv-demo\lib\site-packages\alpaca_trade_api\rest.py", line 160, in _one_request
    resp.raise_for_status()
  File "C:\zipline-demo\venv-demo\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://data.alpaca.markets/v1/bars/day?symbols=AAPL%2CGOOG%2CTSLA&limit=1000&end=2022-06-01T00%3A00%3A00%2B00%3A00
