### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connect call failed ('35.194.67.18', 443)

### ISSUE THREAD

**Issue by cunhafh** [alpacahq/pylivetrader#146] opened 2020-04-21 14:13 UTC
Hi,

While running my script on pythonAnywhere I ran into this issue.

2020-04-20 18:03:46 - Task preparing to start
Apr 20 18:07:11 [2020-04-20 18:07:11.469071] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Apr 20 18:08:00 Initializing...
Apr 20 18:08:00 [2020-04-20 18:08:00.113853] ERROR: Executor: Parser must be a string or character stream, not int
Apr 20 18:08:00 Traceback (most recent call last):
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
Apr 20 18:08:00     func(*args, **kwargs)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
Apr 20 18:08:00     handle_data(algo, current_data, dt_to_use)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
Apr 20 18:08:00     dt,
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
Apr 20 18:08:00     self.callback(context, data)
Apr 20 18:08:00   File "bb.py", line 32, in bollinger_bands
Apr 20 18:08:00     current_price = data.current(context.stock, 'price')
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 85, in current
Apr 20 18:08:00     results = parallelize(fetch)(fetch_args)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/misc/parallel_utils.py", line 39, in wrapper
Apr 20 18:08:00     task_result = task.result()
Apr 20 18:08:00   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
Apr 20 18:08:00     return self.__get_result()
Apr 20 18:08:00   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
Apr 20 18:08:00     raise self._exception
Apr 20 18:08:00   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Apr 20 18:08:00     result = self.fn(*self.args, **self.kwargs)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 73, in fetch
Apr 20 18:08:00     self.data_frequency
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 56, in get_spot_value
Apr 20 18:08:00     assets, field, dt, data_frequency, self.quantopian_compatible
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 445, in get_spot_value
Apr 20 18:08:00     results = self._get_spot_bars(symbols, field)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 466, in _get_spot_bars
Apr 20 18:08:00     symbol_bars = self._symbol_bars(symbols, 'minute', limit=1)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 620, in _symbol_bars
Apr 20 18:08:00     return parallelize(fetch)(symbols)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/misc/parallel_utils.py", line 39, in wrapper
Apr 20 18:08:00     task_result = task.result()
Apr 20 18:08:00   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
Apr 20 18:08:00     return self.__get_result()
Apr 20 18:08:00   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
Apr 20 18:08:00     raise self._exception
Apr 20 18:08:00   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Apr 20 18:08:00     result = self.fn(*self.args, **self.kwargs)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 82, in wrapper
Apr 20 18:08:00     return func(*args, **kwargs)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 583, in fetch
Apr 20 18:08:00     int(to.timestamp()) * 1000
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/polygon/rest.py", line 145, in historic_agg_v2
Apr 20 18:08:00     _from=dateutil.parser.parse(_from).date().isoformat(),
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
Apr 20 18:08:00     return DEFAULTPARSER.parse(timestr, **kwargs)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
Apr 20 18:08:00     res, skipped_tokens = self._parse(timestr, **kwargs)
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
Apr 20 18:08:00     l = _timelex.split(timestr)         # Splits the timestr into tokens
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
Apr 20 18:08:00     return list(cls(s))
Apr 20 18:08:00   File "/home/cunha/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 76, in __init__
Apr 20 18:08:00     '{itype}'.format(itype=instream.__class__.__name__))
Apr 20 18:08:00 TypeError: Parser must be a string or character stream, not int
Apr 20 18:08:00 [2020-04-20 18:08:00.160456] WARNING: Executor: Continuing execution
Apr 21 01:08:43 WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
Apr 21 01:10:36 WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
Apr 21 01:10:36 ERROR:asyncio:Task exception was never retrieved
Apr 21 01:10:36 future: <Task finished coro=<StreamConn._ensure_ws() done, defined at /home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/stream2.py:88> exception=ConnectionRefusedError(111, "Connect call failed ('35.194.67.18', 443)")>
Apr 21 01:10:36 Traceback (most recent call last):
Apr 21 01:10:36   File "/home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 94, in _ensure_ws
Apr 21 01:10:36     await self._connect()
Apr 21 01:10:36   File "/home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 35, in _connect
Apr 21 01:10:36     ws = await websockets.connect(self._endpoint)
Apr 21 01:10:36   File "/home/cunha/venv/lib/python3.6/site-packages/websockets/client.py", line 535, in __await_impl__
Apr 21 01:10:36     transport, protocol = await self._create_connection()
Apr 21 01:10:36   File "/usr/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
Apr 21 01:10:36     raise exceptions[0]
Apr 21 01:10:36   File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
Apr 21 01:10:36     yield from self.sock_connect(sock, address)
Apr 21 01:10:36   File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
Apr 21 01:10:36     return (yield from fut)
Apr 21 01:10:36   File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
Apr 21 01:10:36     raise OSError(err, 'Connect call failed %s' % (address,))
Apr 21 01:10:36 ConnectionRefusedError: [Errno 111] Connect call failed ('35.194.67.18', 443)

Thanks

**Comment by shlomikushchi** [comment] 2020-04-21 14:48
os, so I see here at least 2 different errors. 
one of them is because of a mismatch between versions (we installed a patch branch to handle another issue https://github.com/alpacahq/pylivetrader/issues/127
so that is the cause of that)
the other is a disconnection we get from the server.

let's first clear the log a bit. 
I will create a patch for you. it will clear up the first issue, then we will se if we still get the other ones.

give me 10 minutes

**Comment by shlomikushchi** [comment] 2020-04-21 15:17
install this patch for the alpaca-trade-api-python:
`pip install git+https://github.com/shlomikushchi/alpaca-trade-api-python@stream2_exception_handling -U`

it should take care of the first issue. let's see if we still get the other one

**Comment by shlomikushchi** [comment] 2020-04-21 15:19
install this patch for the alpaca-trade-api-python:
`pip install git+https://github.com/shlomikushchi/alpaca-trade-api-python@stream2_exception_handling -U`

it should take care of the first issue. let's see if we still get the other one

**Comment by shlomikushchi** [comment] 2020-04-21 17:24
any updates?

**Comment by cunhafh** [comment] 2020-04-21 18:01
I’ve made the updates and it’s been running ever since with no warnings. I’ll send you the event log tomorrow, hopefully all will work

Thanks

**Comment by ikosenn** [comment] 2020-04-21 22:26
FYI something is broken in `api-python`. There is no `https://api.polygon.io/v2/meta/symbols/`. The v2

**Comment by cunhafh** [comment] 2020-04-22 12:40
Good day guys,

Here’s the latest log. Thanks

(venv) 15:36 ~ $ pylivetrader run -f bb.py --backend-config config.yaml
[2020-04-21 15:36:34.376050] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Initializing...
Calculating Bollinger bands...
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
WARNING:root:server rejected WebSocket connection: HTTP 502
^[[1;2DWARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
WARNING:root:server rejected WebSocket connection: HTTP 502
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<StreamConn._ensure_ws() done, defined at /home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/stream2.py:88> exception=C
onnectionRefusedError(111, "Connect call failed ('35.194.67.18', 443)")>
Traceback (most recent call last):
  File "/home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 94, in _ensure_ws
    await self._connect()
  File "/home/cunha/venv/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 35, in _connect
    ws = await websockets.connect(self._endpoint)
  File "/home/cunha/venv/lib/python3.6/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('35.194.67.18', 443)

**Comment by shlomikushchi** [comment] 2020-04-22 13:16
can you tell me what time (UTC) it happend? or at least, during trading hours or after?

**Comment by cunhafh** [comment] 2020-04-22 15:23
I do not know, i believe it was after the market closed.

Im running the algo again and will confirm with you tomorrow morning

**Comment by cunhafh** [comment] 2020-04-22 19:02
Shlomi,

It is happening during market hours indeed.

WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
WARNING:root:server rejected WebSocket connection: HTTP 502
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
WARNING:root:server rejected WebSocket connection: HTTP 502

**Comment by shlomikushchi** [comment] 2020-04-23 18:03
so this is going back to the issue. all your stacktraces for this issue are now gone so we will close this issue (let me know otherwise)

regarding the disconnections - it's coming from the server. 
we are corrently releasing a new version which hopefully will give better results.

now, none of these things should influence your usage. 
this is the websocket connection, pylivetrader is using rest api (unless you're doing something special in your code)
but if you wrote your code in `handle_data` and you get the stock price using `data.history` - then you should be able to ignore this warning.
you could check this easily by adding prints to your `handle_data` and check that the data you receive is updated. 

let me know if that is not the case

**Closed** 2020-04-24 14:12 UTC
Labels: bug
